name: Build and Deploy Worker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Use Node 22.20.0
        uses: actions/setup-node@v6
        with:
          node-version: 22.20.0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10.28.2
          run_install: |
            - args: [--frozen-lockfile]

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v5
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Check formatting
        run: pnpm prettier --check "src/**/*.ts"

      - name: Lint
        run: pnpm eslint "src/**/*.ts"

      - name: Run tests
        run: pnpm test

      - name: Deploy to Cloudflare Workers
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
              TMDB_KEY
              TWITCH_CLIENT_ID
              TWITCH_CLIENT_SECRET
              DISCOGS_TOKEN
              GH_TOKEN
              YOUTUBE_KEY
        env:
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          DISCOGS_TOKEN: ${{ secrets.DISCOGS_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}